const KEY="eventdashboard-v2";
const blank=()=>({id:crypto.randomUUID(),createdAt:Date.now(),info:{eventName:"",client:"",eventDate:"",venue:"",room:"",eventType:"",expectedAttendance:"",objective:""},visual:{kv:""},agenda:[],speakers:[],rsvp:{registrations:"",attendees:""},assets:{photos:0,collaterals:0,giveaways:0},survey:false,recap:""});
let state=JSON.parse(localStorage.getItem(KEY)||'{"projects":[]}');
let active=null, tab="info";
const $=s=>document.querySelector(s), app=$("#app");
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function pct(p){let a=[p.info.eventName,p.info.eventDate,p.info.venue,p.visual.kv,p.agenda.length,p.speakers.length,p.rsvp.registrations,p.assets.photos,p.assets.collaterals,p.assets.giveaways,p.survey,p.recap].filter(Boolean).length;return Math.round(a/12*100)}
function header(title,sub,crumb="WORKSPACE",actions=""){ $("#pageTitle").textContent=title;$("#pageSub").textContent=sub;$("#crumb").textContent=crumb;$("#topActions").innerHTML=actions}
function projectList(q=""){
 active=null; header("Projects","管理所有活動專案與結案報告進度","WORKSPACE",`<button class="btn primary" id="newBtn">+ New Project</button>`);
 const list=state.projects.filter(p=>(p.info.eventName+" "+p.info.client).toLowerCase().includes(q.toLowerCase()));
 app.innerHTML=`<div class="summary"><div class="metric"><span>Total Projects</span><strong>${state.projects.length}</strong></div><div class="metric"><span>Report Ready</span><strong>${state.projects.filter(p=>pct(p)>=80).length}</strong></div><div class="metric"><span>In Progress</span><strong>${state.projects.filter(p=>pct(p)>0&&pct(p)<80).length}</strong></div><div class="metric"><span>Average Readiness</span><strong>${state.projects.length?Math.round(state.projects.reduce((a,p)=>a+pct(p),0)/state.projects.length):0}%</strong></div></div>
 <div class="toolbar"><input class="search" id="search" placeholder="Search project / client..." value="${esc(q)}"><span class="hint">${list.length} projects</span></div>
 <div class="project-grid">${list.map(p=>`<article class="project-card" data-id="${p.id}"><div class="kv" ${p.visual.kv?`style="background-image:url('${p.visual.kv}')"`:""}></div><div class="card-body"><div class="client">${esc(p.info.client||"EVENT PROJECT")}</div><h3>${esc(p.info.eventName||"Untitled Event")}</h3><div class="meta">${esc([p.info.eventDate,p.info.venue].filter(Boolean).join(" · ")||"尚未設定活動資訊")}</div><div class="progress-line"><i style="width:${pct(p)}%"></i></div><div class="card-foot"><span>Report readiness</span><b>${pct(p)}%</b></div></div></article>`).join("")}</div>${!list.length?`<div class="empty">目前沒有專案。按右上角 New Project 建立第一場活動。</div>`:""}`;
 $("#newBtn").onclick=openModal; $("#search").oninput=e=>projectList(e.target.value);
 document.querySelectorAll(".project-card").forEach(x=>x.onclick=()=>openProject(x.dataset.id));
}
function openModal(){ $("#modal").classList.remove("hidden") } function closeModal(){ $("#modal").classList.add("hidden");$("#projectForm").reset()}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeModal);
$("#projectForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),p=blank();["eventName","client","eventDate","venue","room","eventType","expectedAttendance","objective"].forEach(k=>p.info[k]=f.get(k)||"");let file=f.get("kv");if(file&&file.size){let r=new FileReader();r.onload=()=>{p.visual.kv=r.result;state.projects.unshift(p);save();closeModal();openProject(p.id)};r.readAsDataURL(file)}else{state.projects.unshift(p);save();closeModal();openProject(p.id)}};
function openProject(id){active=state.projects.find(p=>p.id===id);tab="info";renderProject()}
function renderProject(){let p=active;header(p.info.eventName||"Untitled Event",[p.info.eventDate,p.info.venue,p.info.room].filter(Boolean).join(" · ")||"Project Detail","PROJECT",`<button class="btn secondary" id="backBtn">← Projects</button>`);
 app.innerHTML=`<div class="detail-head"><div class="detail-card"><div class="crumb">${esc(p.info.client||"EVENT PROJECT")}</div><h2>${esc(p.info.eventName||"Untitled Event")}</h2><p class="hint">${esc(p.info.objective||"尚未填寫 Event Objective")}</p><div class="progress-line"><i style="width:${pct(p)}%"></i></div><div class="card-foot"><span>Report readiness</span><b>${pct(p)}%</b></div></div><div class="kv-preview" ${p.visual.kv?`style="background-image:url('${p.visual.kv}')"`:""}>${p.visual.kv?"":"Event KV"}</div></div>
 <div class="tabs">${[["info","Event Info"],["kv","Event KV"],["agenda","Agenda"],["speakers","Speakers"],["rsvp","RSVP / Attendance"],["photos","Event Photos"],["collaterals","Collaterals"],["giveaways","Giveaway"],["survey","Survey"],["recap","Recap"],["report","Report"]].map(([k,n])=>`<button class="tab ${tab===k?"active":""}" data-tab="${k}">${n}</button>`).join("")}</div><div id="tabBody"></div>`;
 $("#backBtn").onclick=()=>projectList();document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{tab=x.dataset.tab;renderProject()});renderTab();
}
function renderTab(){let p=active,b=$("#tabBody");
 if(tab==="info"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>Event Information</h3><span class="badge">AUTO SAVE</span></div><div class="form-grid">${field("Event Name","eventName",p.info.eventName)}${field("Client","client",p.info.client)}${field("Event Date","eventDate",p.info.eventDate,"date")}${field("Venue","venue",p.info.venue)}${field("Room","room",p.info.room)}${field("Event Type","eventType",p.info.eventType)}${field("Expected Attendance","expectedAttendance",p.info.expectedAttendance,"number")}<label class="full">Event Objective<textarea data-info="objective">${esc(p.info.objective)}</textarea></label></div></div>`;bindInfo()}
 else if(tab==="kv"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>Event Key Visual</h3><span class="hint">每一場活動獨立保存</span></div><div class="kv-preview" ${p.visual.kv?`style="background-image:url('${p.visual.kv}')"`:""}>${p.visual.kv?"":"尚未上傳 KV"}</div><label class="upload" style="display:flex;margin-top:14px">Replace / Upload KV<input id="kvFile" type="file" accept="image/*"><span>此 KV 之後會套用至 Report Cover 與視覺元素。</span></label></div>`;$("#kvFile").onchange=e=>readImage(e.target.files[0],x=>{p.visual.kv=x;save();renderProject()})}
 else if(tab==="agenda") repeater("Agenda","agenda",["Time","Topic","Speaker"],["time","topic","speaker"]);
 else if(tab==="speakers") repeater("Speaker Library","speakers",["Name","Title","Company"],["name","title","company"],true);
 else if(tab==="rsvp"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>RSVP / Attendance</h3><span class="hint">下一版接 Excel / CSV 匯入</span></div><div class="form-grid">${simple("Registration","registrations",p.rsvp.registrations)}${simple("Attendance","attendees",p.rsvp.attendees)}</div></div>`;b.querySelectorAll("[data-rsvp]").forEach(x=>x.oninput=e=>{p.rsvp[e.target.dataset.rsvp]=e.target.value;save()})}
 else if(["photos","collaterals","giveaways"].includes(tab)){let map={photos:"Event Photos",collaterals:"Collaterals",giveaways:"Giveaway"},n=p.assets[tab]||0;b.innerHTML=`<div class="panel"><div class="panel-head"><h3>${map[tab]}</h3><button class="btn primary small" id="addAsset">+ Add Placeholder</button></div><p class="hint">目前 ${n} items。下一階段改成真實圖片上傳、分類與 Report 選取。</p></div>`;$("#addAsset").onclick=()=>{p.assets[tab]++;save();renderProject()}}
 else if(tab==="survey"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>Survey</h3><span class="hint">Excel / CSV</span></div><label class="upload">Survey file<input id="surveyFile" type="file" accept=".xlsx,.xls,.csv"><span>${p.survey?"已加入 Survey 資料":"正式解析功能下一階段加入"}</span></label></div>`;$("#surveyFile").onchange=e=>{if(e.target.files[0]){p.survey=true;save();renderProject()}}}
 else if(tab==="recap"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>Recap & Evaluation</h3></div><label class="upload">Highlight / Lowlight / Recommendation<textarea id="recap">${esc(p.recap)}</textarea><span>之後 AI Summary 只根據此處與 Survey 資料生成。</span></label></div>`;$("#recap").oninput=e=>{p.recap=e.target.value;save()}}
 else if(tab==="report"){b.innerHTML=`<div class="panel"><div class="panel-head"><h3>Report Generator</h3><span class="badge">${pct(p)}% READY</span></div><div class="report-box" ${p.visual.kv?`style="background-image:url('${p.visual.kv}')"`:""}><div class="crumb" style="color:white">POST EVENT REPORT</div><h2>${esc(p.info.eventName||"Event Name")}</h2><p>${esc([p.info.eventDate,p.info.venue].filter(Boolean).join(" · ")||"Event Date · Venue")}</p></div><p class="hint">V2 先確認 Project workflow；PPTX Generator 會在資料模組穩定後接上。</p></div>`}
}
function field(l,k,v,t="text"){return `<label>${l}<input data-info="${k}" type="${t}" value="${esc(v)}"></label>`}
function simple(l,k,v){return `<label>${l}<input data-rsvp="${k}" type="number" min="0" value="${esc(v)}"></label>`}
function bindInfo(){$("#tabBody").querySelectorAll("[data-info]").forEach(x=>x.oninput=e=>{active.info[e.target.dataset.info]=e.target.value;save()})}
function repeater(title,key,labels,keys,speaker=false){let b=$("#tabBody"),arr=active[key];b.innerHTML=`<div class="panel"><div class="panel-head"><h3>${title}</h3><button class="btn primary small" id="addRow">+ Add</button></div><div id="rows">${arr.map((o,i)=>`<div class="row ${speaker?"speaker-row":""}" data-i="${i}">${keys.map((k,j)=>`<input data-k="${k}" ${k==="time"?'type="time"':""} placeholder="${labels[j]}" value="${esc(o[k]||"")}">`).join("")}<button class="btn small del">Delete</button></div>`).join("")||`<div class="empty">尚未建立資料</div>`}</div></div>`;$("#addRow").onclick=()=>{arr.push({});save();renderProject()};document.querySelectorAll(".row").forEach(r=>{let i=+r.dataset.i;r.querySelectorAll("input").forEach(x=>x.oninput=e=>{arr[i][e.target.dataset.k]=e.target.value;save()});r.querySelector(".del").onclick=()=>{arr.splice(i,1);save();renderProject()}})}
function readImage(f,cb){if(!f)return;let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>{document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));x.classList.add("active");if(x.dataset.page==="projects")projectList();else{active=null;header("Report Templates","品牌模板之後再加入","WORKSPACE");app.innerHTML=`<div class="empty">Brand / Report Templates 先保留。現在先把共用 Project workflow 做完整。</div>`}});
projectList();
