import {
  auth, db, provider, signInWithPopup, signOut, onAuthStateChanged,
  collection, doc, getDocs, getDoc, setDoc, deleteDoc, serverTimestamp
} from "./firebase.js?v=20260820-popup-v1";

const WORKSPACE_KEY="event-report-workspace-v1";
const LEGACY_KEY="post-event-report-system-v1";
const STRUCTURED=["agenda","speakers","attendees"];
const gate=document.querySelector("#authGate"),systemApp=document.querySelector("#systemApp"),loginBtn=document.querySelector("#googleLoginBtn"),logoutBtn=document.querySelector("#logoutBtn"),authMessage=document.querySelector("#authMessage"),userName=document.querySelector("#userName"),userRole=document.querySelector("#userRole"),usersBtn=document.querySelector("#usersBtn"),usersModal=document.querySelector("#usersModal"),usersList=document.querySelector("#usersList");
let started=false,saveTimer=null,currentRole="viewer",activeUid=null,cloudSaveInstalled=false,viewerObserver=null;
let knownProjectIds=new Set(),knownChildIds=new Map(),lastProjectSignatures=new Map();
const childKey=(pid,type)=>`${pid}:${type}`;
const knownChildren=(pid,type)=>knownChildIds.get(childKey(pid,type))||new Set();
const setKnownChildren=(pid,type,ids)=>knownChildIds.set(childKey(pid,type),new Set(ids));

function showGate(message="請登入以繼續"){gate.classList.remove("auth-hidden");systemApp.classList.add("auth-hidden");authMessage.textContent=message;}
function showApp(user){gate.classList.add("auth-hidden");systemApp.classList.remove("auth-hidden");userName.textContent=user.displayName||user.email||"Signed in";userRole.textContent=currentRole.toUpperCase();userRole.className=`role-chip role-${currentRole}`;usersBtn.style.display=currentRole==="admin"?"":"none";const b=document.querySelector("#newProjectBtn");if(b)b.style.display=currentRole==="viewer"?"none":"";}
function refreshView(){if(!started)return;const n=document.querySelector(".nav-item.active");if(n&&typeof n.onclick==="function")n.onclick();setTimeout(applyRoleMode,0);}

loginBtn.addEventListener("click",async()=>{authMessage.textContent="Opening Google sign-in…";loginBtn.disabled=true;try{const r=await signInWithPopup(auth,provider);if(r?.user)authMessage.textContent="Google 登入成功，正在載入權限…";}catch(e){console.error(e);authMessage.textContent=e?.code==="auth/popup-blocked"?"登入視窗被瀏覽器阻擋，請允許此網站的彈出式視窗後再試一次。":e?.code==="auth/popup-closed-by-user"?"登入視窗已關閉，請再按一次 Continue with Google。":`登入失敗：${e.message}`;}finally{loginBtn.disabled=false;}});
logoutBtn.addEventListener("click",async()=>{usersModal.classList.add("hidden");await signOut(auth);});

async function ensureUserProfile(user){const ref=doc(db,"users",user.uid),snap=await getDoc(ref);if(snap.exists()){const d=snap.data();currentRole=["admin","editor","viewer"].includes(d.role)?d.role:"viewer";await setDoc(ref,{displayName:user.displayName||d.displayName||"",email:user.email||d.email||"",lastLoginAt:serverTimestamp()},{merge:true});return;}currentRole="viewer";await setDoc(ref,{uid:user.uid,displayName:user.displayName||"",email:user.email||"",role:"viewer",createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()});}

function projectCore(project){const p=JSON.parse(JSON.stringify(project||{}));STRUCTURED.forEach(k=>delete p[k]);if(p.visual)p.visual.kvDataUrl="";if(Array.isArray(p.photos))p.photos=p.photos.map(({data,...rest})=>rest);return p;}
function projectSignature(p){const x=JSON.parse(JSON.stringify(p||{}));if(x.visual)x.visual.kvDataUrl="";if(Array.isArray(x.speakers))x.speakers=x.speakers.map(s=>({...s,photo:""}));if(Array.isArray(x.photos))x.photos=x.photos.map(({data,...rest})=>rest);return JSON.stringify(x);}
function mergeLocalAssets(cloud,local){if(!local)return cloud;const m=JSON.parse(JSON.stringify(cloud));if(local.visual?.kvDataUrl)m.visual={...(m.visual||{}),kvDataUrl:local.visual.kvDataUrl};if(Array.isArray(m.speakers)){const lm=new Map((local.speakers||[]).map(s=>[s.id,s]));m.speakers=m.speakers.map(s=>({...s,photo:lm.get(s.id)?.photo||s.photo||""}));}if(Array.isArray(m.photos)){const lm=new Map((local.photos||[]).map(p=>[p.id,p]));m.photos=m.photos.map(p=>({...p,data:lm.get(p.id)?.data||""}));}return m;}

async function readChildCollection(pid,type){const snap=await getDocs(collection(db,"projects",pid,type));const rows=snap.docs.map(d=>({...d.data(),id:d.data()?.id||d.id}));setKnownChildren(pid,type,rows.map(x=>x.id).filter(Boolean));return rows;}
async function migrateLegacyChildren(pid,type,legacy,user){if(currentRole==="viewer"||!Array.isArray(legacy)||!legacy.length)return legacy||[];const rows=legacy.map((source,i)=>({...source,id:source.id||`${type}-${Date.now().toString(36)}-${i}`}));await Promise.all(rows.map(source=>{const clean={...source};if(type==="speakers")clean.photo="";return setDoc(doc(db,"projects",pid,type,source.id),{...clean,updatedBy:user.uid,updatedByEmail:user.email||"",updatedAt:serverTimestamp()},{merge:true});}));setKnownChildren(pid,type,rows.map(x=>x.id));return rows;}
async function hydrateStructuredData(project,raw,user){const pairs=await Promise.all(STRUCTURED.map(async type=>{let rows=await readChildCollection(project.id,type);const legacy=Array.isArray(raw?.[type])?raw[type]:[];if(!rows.length&&legacy.length)rows=await migrateLegacyChildren(project.id,type,legacy,user);return [type,rows.length?rows:legacy];}));const out={...project};pairs.forEach(([type,rows])=>out[type]=rows);return out;}

async function loadProjectsFromFirestore(user){const [snap]=await Promise.all([getDocs(collection(db,"projects"))]);const local=(()=>{try{return JSON.parse(localStorage.getItem(WORKSPACE_KEY)||"null")}catch{return null}})();const localById=new Map((local?.projects||[]).map(p=>[p.id,p]));knownChildIds=new Map();
let projects=await Promise.all(snap.docs.map(async d=>{const raw=d.data()?.data||d.data(),base={...raw,id:raw.id||d.id},hydrated=await hydrateStructuredData(base,raw,user);return mergeLocalAssets(hydrated,localById.get(hydrated.id));}));
if(!projects.length&&currentRole!=="viewer"){let migration=local;if(!migration){const legacy=localStorage.getItem(LEGACY_KEY);if(legacy)try{const p=JSON.parse(legacy);migration={projects:[p],activeId:p.id||null};}catch{}}if(migration?.projects?.length){await Promise.all(migration.projects.filter(p=>p.id).map(async p=>{await setDoc(doc(db,"projects",p.id),{data:projectCore(p),createdBy:user.uid,createdByEmail:user.email||"",updatedBy:user.uid,updatedByEmail:user.email||"",updatedAt:serverTimestamp()},{merge:true});await Promise.all(STRUCTURED.map(type=>migrateLegacyChildren(p.id,type,p[type]||[],user)));}));projects=migration.projects;}}
knownProjectIds=new Set(projects.map(p=>p.id).filter(Boolean));lastProjectSignatures=new Map(projects.map(p=>[p.id,projectSignature(p)]));localStorage.setItem(WORKSPACE_KEY,JSON.stringify({projects,activeId:local?.activeId||null}));}

async function syncChildCollection(pid,type,rows,user){const current=Array.isArray(rows)?rows:[],currentIds=new Set();const writes=current.map((source,i)=>{const id=source.id||`${type}-${Date.now().toString(36)}-${i}`;source.id=id;currentIds.add(id);const clean={...source,id};if(type==="speakers")clean.photo="";return setDoc(doc(db,"projects",pid,type,id),{...clean,updatedBy:user.uid,updatedByEmail:user.email||"",updatedAt:serverTimestamp()},{merge:true});});const deletes=[...knownChildren(pid,type)].filter(id=>!currentIds.has(id)).map(id=>deleteDoc(doc(db,"projects",pid,type,id)));await Promise.all([...writes,...deletes]);setKnownChildren(pid,type,currentIds);}
async function syncProject(p,user){await Promise.all([setDoc(doc(db,"projects",p.id),{data:projectCore(p),updatedBy:user.uid,updatedByEmail:user.email||"",updatedAt:serverTimestamp(),...(knownProjectIds.has(p.id)?{}:{createdBy:user.uid,createdByEmail:user.email||""})},{merge:true}),...STRUCTURED.map(type=>syncChildCollection(p.id,type,p[type]||[],user))]);lastProjectSignatures.set(p.id,projectSignature(p));}
async function syncWorkspaceToFirestore(workspace,user){if(!user||currentRole==="viewer")return;const projects=workspace?.projects||[],currentIds=new Set(projects.map(p=>p.id).filter(Boolean));const changed=projects.filter(p=>p.id&&lastProjectSignatures.get(p.id)!==projectSignature(p));await Promise.all(changed.map(p=>syncProject(p,user)));if(currentRole==="admin")await Promise.all([...knownProjectIds].filter(id=>!currentIds.has(id)).map(id=>deleteDoc(doc(db,"projects",id))));knownProjectIds=currentIds;}
function installCloudSave(){if(cloudSaveInstalled)return;cloudSaveInstalled=true;const nativeSet=localStorage.setItem.bind(localStorage);localStorage.setItem=function(key,value){nativeSet(key,value);if(key!==WORKSPACE_KEY||currentRole==="viewer")return;clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const user=auth.currentUser;if(!user||user.uid!==activeUid)return;const s=document.querySelector("#saveState");if(s)s.textContent="Saving…";await syncWorkspaceToFirestore(JSON.parse(value),user);if(s)s.textContent="Saved to Firestore";}catch(e){console.error(e);const s=document.querySelector("#saveState");if(s)s.textContent=e?.code==="permission-denied"?"Permission denied":"Firestore save failed";}},700);};}

function enhanceSpeakerFields(){const cards=[...document.querySelectorAll("#speakerGrid .speaker-card")];if(!cards.length)return;let w;try{w=JSON.parse(localStorage.getItem(WORKSPACE_KEY)||"null");}catch{return}const p=(w?.projects||[]).find(x=>x.id===w.activeId);if(!p)return;cards.forEach((card,i)=>{const s=p.speakers?.[i],fields=card.querySelector(".speaker-fields");if(!s||!fields)return;const english=fields.querySelector('input[data-k="name"]'),titleInput=fields.querySelector('input[data-k="title"]'),companyInput=fields.querySelector('input[data-k="company"]');if(english)english.placeholder="English Name";if(titleInput)titleInput.placeholder="Title";if(companyInput)companyInput.placeholder="Company";if(!fields.querySelector('input[data-speaker-zh]')){const zh=document.createElement("input");zh.type="text";zh.placeholder="中文姓名";zh.value=s.zhName||"";zh.dataset.speakerZh="1";zh.oninput=e=>{let ww;try{ww=JSON.parse(localStorage.getItem(WORKSPACE_KEY)||"null")}catch{return}const pp=(ww?.projects||[]).find(x=>x.id===ww.activeId),ss=pp?.speakers?.[i];if(!ss)return;ss.zhName=e.target.value;localStorage.setItem(WORKSPACE_KEY,JSON.stringify(ww));};if(english?.nextSibling)fields.insertBefore(zh,english.nextSibling);else fields.prepend(zh);}});}
function applyRoleMode(){const root=document.querySelector("#viewRoot");if(!root)return;enhanceSpeakerFields();const controls=root.querySelectorAll("input,textarea,select"),actions=root.querySelectorAll(".button.primary,.button.danger,.mini-upload,.file-button");if(currentRole==="viewer"){controls.forEach(e=>e.disabled=true);actions.forEach(e=>e.style.display="none");const s=document.querySelector("#saveState");if(s)s.textContent="View only";}else{controls.forEach(e=>e.disabled=false);actions.forEach(e=>e.style.display="");}if(!viewerObserver){viewerObserver=new MutationObserver(()=>{enhanceSpeakerFields();const r=document.querySelector("#viewRoot");if(!r)return;if(currentRole==="viewer"){r.querySelectorAll("input,textarea,select").forEach(e=>e.disabled=true);r.querySelectorAll(".button.primary,.button.danger,.mini-upload,.file-button").forEach(e=>e.style.display="none");}});viewerObserver.observe(root,{childList:true,subtree:true});}}

async function renderUsers(){if(currentRole!=="admin")return;const snap=await getDocs(collection(db,"users")),adminIds=snap.docs.filter(d=>d.data()?.role==="admin").map(d=>d.id);usersList.innerHTML=snap.docs.map(d=>{const u=d.data();return `<div class="user-row"><div><strong>${u.displayName||"Unnamed"}</strong><span>${u.email||""}</span></div><select data-uid="${d.id}" data-original="${u.role||"viewer"}"><option value="admin" ${u.role==="admin"?"selected":""}>Admin</option><option value="editor" ${u.role==="editor"?"selected":""}>Editor</option><option value="viewer" ${u.role==="viewer"?"selected":""}>Viewer</option></select></div>`}).join("")||'<div class="empty">No users yet.</div>';usersList.querySelectorAll("select[data-uid]").forEach(sel=>sel.onchange=async()=>{const uid=sel.dataset.uid,old=sel.dataset.original||"viewer",next=sel.value;if(old==="admin"&&adminIds.length===1&&next!=="admin"){alert("系統至少需要保留一位 Admin，最後一位 Admin 不能降級。");sel.value="admin";return;}try{await setDoc(doc(db,"users",uid),{role:next,updatedAt:serverTimestamp()},{merge:true});sel.dataset.original=next;if(uid===auth.currentUser?.uid){currentRole=next;showApp(auth.currentUser);refreshView();}await renderUsers();}catch(e){console.error(e);alert("角色更新失敗：你目前沒有這個操作權限。");sel.value=old;}});}
usersBtn.addEventListener("click",async()=>{if(currentRole!=="admin")return;usersModal.classList.remove("hidden");await renderUsers();});document.querySelectorAll("[data-close-users]").forEach(x=>x.addEventListener("click",()=>usersModal.classList.add("hidden")));

async function loadSession(user){currentRole="viewer";activeUid=user.uid;authMessage.textContent="Loading user permissions…";await ensureUserProfile(user);authMessage.textContent="Loading shared projects…";await loadProjectsFromFirestore(user);showApp(user);}
onAuthStateChanged(auth,async user=>{if(!user){activeUid=null;currentRole="viewer";loginBtn.disabled=false;usersModal.classList.add("hidden");showGate("請使用 Google 帳號登入");return;}try{const previousUid=activeUid;await loadSession(user);const switched=previousUid!==null&&previousUid!==user.uid;if(!started){installCloudSave();started=true;await import("./app.js?v=20260820-subcollections-v1");applyRoleMode();}else if(switched||previousUid===user.uid)refreshView();}catch(e){console.error(e);activeUid=null;currentRole="viewer";showGate(`Firebase 連線失敗：${e.message}`);}});